services:
  api:
    build:
      target: builder
    command: npx nodemon
    environment:
      NODE_ENV: development
    volumes:
      - ./api/src:/app/src
      - ./api/migrations:/app/migrations
      - uploads:${UPLOAD_DIR:-/app/uploads}

  client:
    build:
      context: ./client
      target: builder
    command: npx vite --host
    environment:
      VITE_API_URL: http://api:3000
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
